app:
  redis:
    enable: true
  integration:
    base-url: http://localhost:8082
  cache:
    cache-type: redis
    cache-names:
      - databaseEntities
      - databaseEntityByName
      - databaseEntityById
    caches:
      databaseEntities:
        expiry: 15s
      databaseEntityByName:
        expiry: 15s
      databaseEntityById:
        expiry: 1m


spring:
  data:
    redis:
      host: localhost
      port: 6379

  jpa:
    generate-ddl: true
  datasource:
    url: jdbc:postgresql://localhost:5437/app_db
    username: postgres
    password: postgres
    hikari:
      schema: app_schema
      connection-init-sql: CREATE SCHEMA IF NOT EXISTS app_schema
      connection-timeout: 10000
