spring:
  application:
    name: demo-spring-kafka-app
  kafka:
    bootstrap-servers: localhost:9092

app:
  kafka:
    kafkaMessageTopic: "message-topic"
    kafkaMessageGroupId: "kafka-message-group-id"
